### ISSUE TITLE
Pee pee poo poo can delete

### ISSUE THREAD

**Issue by mat1jaczyyy** [vaaski/apollo-studio-web#3]
Yes

**Comment by vaaski** [comment]
alrighty

**Comment by mat1jaczyyy** [comment]
but you didnt delete it yet nerd

**Comment by vaaski** [comment]
how to delete

**Comment by mat1jaczyyy** [comment]
[how to google](https://help.github.com/en/articles/creating-and-deleting-branches-within-your-repository#deleting-a-branch)

**Comment by vaaski** [comment]
n word

![Screenshot_20190801-194556_edit](https://user-images.githubusercontent.com/17879327/62315254-41e27e00-b495-11e9-9f0b-632438bcab0f.jpg)

**Comment by mat1jaczyyy** [comment]
i have deleted
